name: Inject API Key

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject API Key into config.js
        run: echo "const CONFIG = { GOOGLE_MAPS_API_KEY: '${{ secrets.GOOGLE_MAPS_API_KEY }}' };" > config.js

      - name: Commit updated config.js
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add config.js
          git commit -m "Injected API key" || echo "No changes to commit"
          git push